- name: KVM_install
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:
  
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Install qemu-kvm
      apt:
        name: qemu-kvm
        state: latest

    - name: Install libvirt-clients
      apt:
        name: libvirt-clients
        state: latest

    - name: Install libvirt-daemon-system
      apt:
        name: libvirt-daemon-system
        state: latest   
