- name: KVM_setup
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:

    - name: Set authorized key taken from file (vovkas)
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/vovkas.pub') }}"

    - name: Set authorized key taken from file (yeguch)
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/yeguch.pub') }}"
        
    - name: Set authorized key taken from file (noir)
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/root/.ssh/noir.pub') }}"


    - name: Disable Password Authentication
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp='^PasswordAuthentication'
        line="PasswordAuthentication no"
        state=present
        backup=yes


    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Install qemu-kvm
      apt:
        name: qemu-kvm
        state: latest

    - name: Install libvirt-clients
      apt:
        name: libvirt-clients
        state: latest

    - name: Install libvirt-daemon-system
      apt:
        name: libvirt-daemon-system
        state: latest   

#First try to copy file

#    - name: Download win16 file
#      become: true
#      shell: "scp root@172.255.230.76:/var/lib/libvirt/images/win2k16.qcow2 /var/lib/libvirt/images/"

#Second try to copy file

#    - name: Transfer file from 172.255.230.76 to host
#      synchronize:
#        src: /var/lib/libvirt/images/win2k16.qcow2
#        dest: /var/lib/libvirt/images/
#      delegate_to: 172.255.230.76